const roles={leadership:{name:'Leadership & Coordination',short:'Leadership',desc:'You may help teams clarify next steps, communicate early, and keep complicated work moving.'},photography:{name:'Photography',short:'Photography',desc:'You may be energized by anticipating moments, working respectfully with people, and delivering usable images.'},design:{name:'Design',short:'Design',desc:'You may notice hierarchy, rhythm, typography, spacing, and how the shared visual system guides a reader.'},coverage:{name:'Alternative Coverage',short:'Coverage',desc:'You may find the revealing quote, poll, detail, statistic, or mini-story that makes a spread less predictable.'},journalism:{name:'Journalism',short:'Journalism',desc:'You may be drawn to interviewing, verifying, representing people fairly, and discovering the story beneath an event.'},finishing:{name:'Finishing & Quality Control',short:'Finishing',desc:'You may bring patience, accuracy, fact-checking, and the ability to repair small defects before publication.'}};
const roleChoices=Object.entries(roles).map(([value,r])=>({value,label:r.name}));
const steps=[
 {title:'Current skill evidence',subtitle:'Rate what you can do today—not what you think you should already know.',questions:[
  {id:'photoCraft',type:'scale',text:'Photography: composition, timing, focus, exposure, and respectful interaction',role:'photography'},
  {id:'photoFiles',type:'scale',text:'Selecting, naming, transferring, organizing, and backing up photographs',role:'photography'},
  {id:'interview',type:'scale',text:'Approaching unfamiliar people and conducting an interview',role:'journalism'},
  {id:'captions',type:'scale',text:'Writing captions that identify people and add information beyond the photograph',role:'journalism'},
  {id:'designCraft',type:'scale',text:'Page design: hierarchy, typography, spacing, grids, and visual flow',role:'design'},
  {id:'alternative',type:'scale',text:'Finding sidebar ideas, statistics, quotes, polls, or alternative forms of coverage',role:'coverage'},
  {id:'accuracy',type:'scale',text:'Fact-checking, proofreading names, and noticing small inconsistencies',role:'finishing'},
  {id:'planning',type:'scale',text:'Planning multi-step work and meeting checkpoints without repeated reminders',role:'leadership'},
  {id:'evidence',type:'textarea',text:'Choose your two highest ratings. What real experience or product supports them?',placeholder:'A project, job, team responsibility, performance, or product…'}]},
 {title:'Role instinct',subtitle:'Choose the contribution you would be most willing to own—not the one that sounds impressive.',questions:[
  {id:'event',type:'choice',text:'A major event is tomorrow, but coverage is still vague. Which kind of work would you naturally take first?',options:roleChoices},
  {id:'unclearStory',type:'choice',text:'A spread has plenty of material but does not yet tell a clear story. Where would you contribute?',options:roleChoices},
  {id:'almostReady',type:'choice',text:'Deadline is approaching and the page is almost—but not quite—ready. Which responsibility would you accept?',options:roleChoices},
  {id:'underrepresented',type:'choice',text:'An important group says it rarely appears meaningfully in the yearbook. Which response best fits you?',options:roleChoices},
  {id:'thinSpread',type:'choice',text:'The main story is solid, but the spread still feels thin or predictable. Where would you contribute?',options:roleChoices},
  {id:'topAppeal',type:'textarea',text:'Which two lenses attract you most, and what is appealing about each?',placeholder:'Two lenses and why…'}]},
 {title:'Production habits',subtitle:'Publishing reveals how we respond when plans become inconvenient or uncertain.',questions:[
  {id:'conflict',type:'textarea',text:'At 7 p.m. you realize you cannot cover tomorrow morning’s event. What exactly should you do, and when?',placeholder:'Be specific about communication and timing…'},
  {id:'source',type:'textarea',text:'You contacted someone twice and still need an interview. What are your next three steps?',placeholder:'Step 1… Step 2… Step 3…'},
  {id:'disagreement',type:'textarea',text:'A teammate is attached to a photo or design choice you believe weakens the page. How would you handle it?',placeholder:'Describe what you would say or do…'},
  {id:'reliability',type:'textarea',text:'Describe one commitment you maintained over time. What helped you follow through?',placeholder:'A real commitment and the structure that helped…'}]},
 {title:'Placement and growth',subtitle:'Strong crews balance present ability with meaningful opportunities to learn.',questions:[
  {id:'firstRoles',type:'multi',max:3,text:'Choose up to three responsibilities you would be excited to try first.',options:[{value:'photography',label:'Photography'},{value:'journalism',label:'Reporting / interviewing'},{value:'journalism',label:'Caption or feature writing'},{value:'design',label:'Page design'},{value:'coverage',label:'Sidebars / alternative coverage'},{value:'finishing',label:'Copyediting / fact-checking'},{value:'finishing',label:'Photo / file management'},{value:'leadership',label:'Project tracking or leadership'},{value:'explore',label:'Explore before choosing'}]},
  {id:'growth',type:'textarea',text:'Which skill do you most want to develop this year? Why does it matter to you?',placeholder:'A skill and why…'},
  {id:'energy',type:'textarea',text:'Which responsibility sounds energizing? Which sounds stressful? Explain both.',placeholder:'Energizing… Stressful…'},
  {id:'support',type:'textarea',text:'What support, structure, or feedback helps you do your most reliable work?',placeholder:'Think about reminders, examples, check-ins, quiet work, feedback…'},
  {id:'missing',type:'textarea',optional:true,text:'What can you do—inside or outside school—that this compass failed to ask about?',placeholder:'Optional'}]}
];
let current=0;const answers={};
const el=id=>document.getElementById(id);
el('startBtn').addEventListener('click',()=>{if(!el('studentName').value.trim()){el('studentName').focus();return}el('intro').classList.add('hidden');el('survey').classList.remove('hidden');renderStep();scrollTo({top:0,behavior:'smooth'})});
function renderStep(){const step=steps[current],pct=Math.round((current+1)/steps.length*100);el('stepLabel').textContent=`Step ${current+1} of ${steps.length}`;el('progressPercent').textContent=`${pct}%`;el('progressBar').style.width=`${pct}%`;el('backBtn').style.visibility=current?'visible':'hidden';el('nextBtn').textContent=current===steps.length-1?'See my profile →':'Continue →';el('formMessage').textContent='';el('questionStage').innerHTML=`<section class="stage"><div class="stage-intro"><p class="eyebrow dark">Step ${current+1}</p><h2>${step.title}</h2><p>${step.subtitle}</p></div>${step.questions.map((q,i)=>questionHTML(q,i)).join('')}</section>`;restore();bindLimits()}
function questionHTML(q,i){const n=steps.slice(0,current).reduce((a,s)=>a+s.questions.length,0)+i+1;let field='';if(q.type==='scale'){const labels=['Entirely new','Some exposure','Can do with help','Strong & independent','Could coach'];field=`<div class="scale">${labels.map((x,j)=>`<label class="scale-option"><input type="radio" name="${q.id}" value="${j+1}"><strong>${j+1}</strong><span>${x}</span></label>`).join('')}</div>`}else if(q.type==='choice'||q.type==='multi'){const t=q.type==='multi'?'checkbox':'radio';field=`<div class="choice">${q.options.map((o,j)=>`<label class="choice-option"><input type="${t}" name="${q.id}" value="${o.value}" data-label="${o.label}"><span>${o.label}</span></label>`).join('')}</div>${q.max?`<span class="hint">Select no more than ${q.max}.</span>`:''}`}else field=`<textarea name="${q.id}" rows="4" placeholder="${q.placeholder||''}"></textarea>`;return `<div class="question" data-question="${q.id}"><span class="question-title"><span class="question-number">${n}</span>${q.text}${q.optional?' <em>(optional)</em>':''}</span>${field}</div>`}
function saveVisible(){steps[current].questions.forEach(q=>{const nodes=[...document.querySelectorAll(`[name="${q.id}"]`)];if(q.type==='scale'||q.type==='choice'){const x=nodes.find(n=>n.checked);answers[q.id]=x?x.value:''}else if(q.type==='multi'){answers[q.id]=nodes.filter(n=>n.checked).map(n=>({value:n.value,label:n.dataset.label}))}else answers[q.id]=nodes[0]?.value.trim()||''})}
function restore(){steps[current].questions.forEach(q=>{const nodes=[...document.querySelectorAll(`[name="${q.id}"]`)];if(q.type==='multi'){const selected=(answers[q.id]||[]).map(x=>x.label);nodes.forEach(n=>n.checked=selected.includes(n.dataset.label))}else if(q.type==='scale'||q.type==='choice')nodes.forEach(n=>n.checked=n.value===answers[q.id]);else if(nodes[0])nodes[0].value=answers[q.id]||''})}
function bindLimits(){steps[current].questions.filter(q=>q.type==='multi').forEach(q=>document.querySelectorAll(`[name="${q.id}"]`).forEach(n=>n.addEventListener('change',()=>{const checked=[...document.querySelectorAll(`[name="${q.id}"]:checked`)];if(checked.length>q.max){n.checked=false;el('formMessage').textContent=`Choose no more than ${q.max} responsibilities.`}})))}
function valid(){saveVisible();const missing=steps[current].questions.find(q=>!q.optional&&(!answers[q.id]||(Array.isArray(answers[q.id])&&!answers[q.id].length)));if(missing){el('formMessage').textContent='Please answer each question before continuing.';document.querySelector(`[data-question="${missing.id}"]`)?.scrollIntoView({behavior:'smooth',block:'center'});return false}return true}
el('nextBtn').addEventListener('click',()=>{if(!valid())return;if(current<steps.length-1){current++;renderStep();scrollTo({top:0,behavior:'smooth'})}else showResults()});el('backBtn').addEventListener('click',()=>{saveVisible();current--;renderStep();scrollTo({top:0,behavior:'smooth'})});
function calculate(){const scores=Object.fromEntries(Object.keys(roles).map(k=>[k,0]));steps[0].questions.filter(q=>q.role).forEach(q=>scores[q.role]+=Number(answers[q.id]||0));steps[1].questions.filter(q=>q.type==='choice').forEach(q=>scores[answers[q.id]]+=4);(answers.firstRoles||[]).forEach(x=>{if(scores[x.value]!==undefined)scores[x.value]+=3});const max=Math.max(...Object.values(scores));return{scores,ranked:Object.keys(scores).sort((a,b)=>scores[b]-scores[a]),max}}
function showResults(){el('survey').classList.add('hidden');el('results').classList.remove('hidden');const {scores,ranked,max}=calculate(),name=el('studentName').value.trim();el('resultTitle').textContent=`${name}'s Role Compass`;el('topRoles').innerHTML=ranked.slice(0,2).map((k,i)=>`<article class="role-card"><div class="rank">${i?'Second signal':'Strongest signal'}</div><h3>${roles[k].name}</h3><p>${roles[k].desc}</p></article>`).join('');el('scoreBars').innerHTML=ranked.map(k=>`<div class="score-row"><div class="score-label"><span>${roles[k].short}</span><span>${scores[k]}</span></div><div class="score-track"><div class="score-fill" style="width:${Math.max(5,scores[k]/max*100)}%"></div></div></div>`).join('');el('interpretation').innerHTML=`<div class="interpret-block"><strong>Lead with:</strong> ${roles[ranked[0]].name} and ${roles[ranked[1]].name}. These are starting signals, not guaranteed assignments.</div><div class="interpret-block"><strong>Remember:</strong> A balanced profile can be as valuable as a dramatic peak. Every published page crosses several lenses.</div><div class="interpret-block"><strong>Next conversation:</strong> Your written evidence, production habits, schedule, and growth goals matter alongside these scores.</div>`;el('summaryText').value=makeSummary(ranked,scores);scrollTo({top:0,behavior:'smooth'})}
function makeSummary(ranked,scores){const first=(answers.firstRoles||[]).map(x=>x.label).join(', ');return `SKYLINE YEARBOOK ROLE COMPASS — 2026–2027\nStudent: ${el('studentName').value.trim()}\nPeriod: ${el('classPeriod').value.trim()||'Not entered'}\n\nPROFILE RANKING\n${ranked.map((k,i)=>`${i+1}. ${roles[k].name} — ${scores[k]} points`).join('\n')}\n\nCURRENT-SKILL EVIDENCE\n${answers.evidence}\n\nROLES I WOULD TRY FIRST\n${first}\n\nTWO LENSES THAT ATTRACT ME\n${answers.topAppeal}\n\nPRODUCTION-HABIT RESPONSES\nCoverage conflict: ${answers.conflict}\nUnresponsive source: ${answers.source}\nQuality disagreement: ${answers.disagreement}\nReliability example: ${answers.reliability}\n\nGROWTH AND SUPPORT\nGrowth goal: ${answers.growth}\nEnergy/stress: ${answers.energy}\nHelpful support: ${answers.support}\nSomething else I bring: ${answers.missing||'No additional response'}\n\nThis profile is a starting point, not a permanent label or promise of a role.`}
el('copyBtn').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(el('summaryText').value);el('copyStatus').textContent='Summary copied. Paste it into the Canvas submission.'}catch{el('summaryText').select();document.execCommand('copy');el('copyStatus').textContent='Summary selected and copied.'}});el('downloadBtn').addEventListener('click',()=>{const blob=new Blob([el('summaryText').value],{type:'text/plain'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`yearbook-role-compass-${el('studentName').value.trim().replace(/[^a-z0-9]+/gi,'-').toLowerCase()}.txt`;a.click();URL.revokeObjectURL(a.href)});el('printBtn').addEventListener('click',()=>print());el('restartBtn').addEventListener('click',()=>{if(confirm('Clear these responses and start again?'))location.reload()});
